---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: gpu-dashboard
  name: dashboard-view
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "watch", "list"]
